### ISSUE TITLE
make fails when running in ubuntu container

### ISSUE THREAD

**Issue by RIKIKU** [pvachon/tsl#4] opened 2020-05-21 02:41 UTC
### Start a new docker container using ubuntu and interactive bash.
`sudo docker run -it ubuntu /bin/bash`
### Install prerequisite stuff
`apt-get update && apt-get -y install build-essential git libjansson-dev libck-dev cmake python pkg-config`
### Attempt to make the app
`git clone https://github.com/pvachon/tsl.git /tmp/tsl`
`mkdir /tmp/tsl/build`
`cd /tmp/tsl/build && cmake .. && make && make install`
### Make output
`cd /tmp/tsl/build && cmake .. && make && make install`
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'ck'
--   Found ck, version 0.6.0
-- Checking for module 'jansson'
--   Found jansson, version 2.11
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tsl/build
Scanning dependencies of target tsl
[  2%] Building C object tsl/CMakeFiles/tsl.dir/assert.c.o
[  4%] Building C object tsl/CMakeFiles/tsl.dir/cpumask.c.o
[  6%] Building C object tsl/CMakeFiles/tsl.dir/diag.c.o
[  9%] Building C object tsl/CMakeFiles/tsl.dir/errors.c.o
[ 11%] Building C object tsl/CMakeFiles/tsl.dir/frame_alloc.c.o
[ 13%] Building C object tsl/CMakeFiles/tsl.dir/hexdump.c.o
[ 16%] Building C object tsl/CMakeFiles/tsl.dir/panic.c.o
[ 18%] Building C object tsl/CMakeFiles/tsl.dir/parsers.c.o
[ 20%] Building C object tsl/CMakeFiles/tsl.dir/printf_helpers.c.o
[ 23%] Building C object tsl/CMakeFiles/tsl.dir/rbtree.c.o
[ 25%] Building C object tsl/CMakeFiles/tsl.dir/safe_alloc.c.o
[ 27%] Building C object tsl/CMakeFiles/tsl.dir/safe_string.c.o
[ 30%] Building C object tsl/CMakeFiles/tsl.dir/threading.c.o
[ 32%] Building C object tsl/CMakeFiles/tsl.dir/time.c.o
[ 34%] Building C object tsl/CMakeFiles/tsl.dir/version.c.o
[ 37%] Building C object tsl/CMakeFiles/tsl.dir/worker_thread.c.o
[ 39%] Building C object tsl/CMakeFiles/tsl.dir/alloc/allocator.c.o
[ 41%] Linking C static library libtsl.a
[ 41%] Built target tsl
Scanning dependencies of target version_dump
[ 44%] Building C object tsl/CMakeFiles/version_dump.dir/version_dump/version_dump.c.o
[ 46%] Linking C executable version_dump
[ 46%] Built target version_dump
Scanning dependencies of target test_tsl
[ 48%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_alloc.c.o
[ 51%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_cpumask.c.o
[ 53%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_main.c.o
[ 55%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_printf_helpers.c.o
[ 58%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_rbtree.c.o
[ 60%] Building C object tsl/test/CMakeFiles/test_tsl.dir/test_refcnt.c.o
[ 62%] Linking C executable test_tsl
[ 62%] Built target test_tsl
Scanning dependencies of target tslapp
[ 65%] Building C object app/CMakeFiles/tslapp.dir/app.c.o
[ 67%] Building C object app/CMakeFiles/tslapp.dir/cpufeatures.c.o
[ 69%] Linking C static library libtslapp.a
[ 69%] Built target tslapp
Scanning dependencies of target tslconfig
[ 72%] Building C object config/CMakeFiles/tslconfig.dir/engine.c.o
[ 74%] Building C object config/CMakeFiles/tslconfig.dir/util.c.o
[ 76%] Linking C static library libtslconfig.a
[ 76%] Built target tslconfig
Scanning dependencies of target tsltestframework
[ 79%] Building C object test/CMakeFiles/tsltestframework.dir/assert.c.o
[ 81%] Building C object test/CMakeFiles/tsltestframework.dir/filesystem.c.o
[ 83%] Building C object test/CMakeFiles/tsltestframework.dir/framework.c.o
[ 86%] Building C object test/CMakeFiles/tsltestframework.dir/main.c.o
[ 88%] Building C object test/CMakeFiles/tsltestframework.dir/malloc_helpers.c.o
[ 90%] Linking C static library libtsltestframework.a
[ 90%] Built target tsltestframework
Scanning dependencies of target test_app
[ 93%] Building C object app/test/CMakeFiles/test_app.dir/test_app.c.o
[ 95%] Linking C executable test_app
../../config/libtslconfig.a(engine.c.o): In function `json_decref':
/usr/include/jansson.h:129: undefined reference to `json_delete'
../../config/libtslconfig.a(engine.c.o): In function `__config_from_json':
/tmp/tsl/config/engine.c:74: undefined reference to `json_array_size'
/tmp/tsl/config/engine.c:78: undefined reference to `json_integer_value'
/tmp/tsl/config/engine.c:82: undefined reference to `json_string_value'
/tmp/tsl/config/engine.c:94: undefined reference to `json_real_value'
../../config/libtslconfig.a(engine.c.o): In function `config_new':
/tmp/tsl/config/engine.c:124: undefined reference to `json_object'
../../config/libtslconfig.a(engine.c.o): In function `config_add':
/tmp/tsl/config/engine.c:162: undefined reference to `json_load_file'
/tmp/tsl/config/engine.c:170: undefined reference to `json_object_update'
../../config/libtslconfig.a(engine.c.o): In function `config_add_string':
/tmp/tsl/config/engine.c:269: undefined reference to `json_loads'
/tmp/tsl/config/engine.c:277: undefined reference to `json_object_update'
../../config/libtslconfig.a(engine.c.o): In function `config_get':
/tmp/tsl/config/engine.c:333: undefined reference to `json_object_get'
../../config/libtslconfig.a(engine.c.o): In function `config_serialize':
/tmp/tsl/config/engine.c:354: undefined reference to `json_dumps'
../../config/libtslconfig.a(engine.c.o): In function `config_array_at':
/tmp/tsl/config/engine.c:426: undefined reference to `json_array_size'
/tmp/tsl/config/engine.c:431: undefined reference to `json_array_get'
collect2: error: ld returned 1 exit status
app/test/CMakeFiles/test_app.dir/build.make:98: recipe for target 'app/test/test_app' failed
make[2]: *** [app/test/test_app] Error 1
CMakeFiles/Makefile2:296: recipe for target 'app/test/CMakeFiles/test_app.dir/all' failed
make[1]: *** [app/test/CMakeFiles/test_app.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RIKIKU** [comment] 2020-05-21 03:47
interestingly, when running this on a Debian container, it seems to work, however, I did have to install ConcurrencyKit from source as the package was not found in apt-get.

**Comment by pvachon** [comment] 2020-05-22 16:49
Hi! Would you be able to post the output of a build when you invoke `make` with the argument `VERBOSE=1`? I suspect we're running up against a link ordering issue. I normally develop against Debian and Armbian, so that might explain how there could be a difference in behaviour.

**Comment by RIKIKU** [comment] 2020-05-22 22:22
sure, here ya go

`cd /tmp/tsl/build && cmake .. && make VERBOSE=1 && make install`
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tsl/build
/usr/bin/cmake -H/tmp/tsl -B/tmp/tsl/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/tsl/build/CMakeFiles /tmp/tsl/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/tmp/tsl/build'
make -f tsl/CMakeFiles/tsl.dir/build.make tsl/CMakeFiles/tsl.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/tsl /tmp/tsl/build /tmp/tsl/build/tsl /tmp/tsl/build/tsl/CMakeFiles/tsl.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f tsl/CMakeFiles/tsl.dir/build.make tsl/CMakeFiles/tsl.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'tsl/CMakeFiles/tsl.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 41%] Built target tsl
make -f tsl/CMakeFiles/version_dump.dir/build.make tsl/CMakeFiles/version_dump.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/tsl /tmp/tsl/build /tmp/tsl/build/tsl /tmp/tsl/build/tsl/CMakeFiles/version_dump.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f tsl/CMakeFiles/version_dump.dir/build.make tsl/CMakeFiles/version_dump.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'tsl/CMakeFiles/version_dump.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 46%] Built target version_dump
make -f tsl/test/CMakeFiles/test_tsl.dir/build.make tsl/test/CMakeFiles/test_tsl.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/tsl/test /tmp/tsl/build /tmp/tsl/build/tsl/test /tmp/tsl/build/tsl/test/CMakeFiles/test_tsl.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f tsl/test/CMakeFiles/test_tsl.dir/build.make tsl/test/CMakeFiles/test_tsl.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'tsl/test/CMakeFiles/test_tsl.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 62%] Built target test_tsl
make -f app/CMakeFiles/tslapp.dir/build.make app/CMakeFiles/tslapp.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/app /tmp/tsl/build /tmp/tsl/build/app /tmp/tsl/build/app/CMakeFiles/tslapp.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f app/CMakeFiles/tslapp.dir/build.make app/CMakeFiles/tslapp.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'app/CMakeFiles/tslapp.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 69%] Built target tslapp
make -f config/CMakeFiles/tslconfig.dir/build.make config/CMakeFiles/tslconfig.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/config /tmp/tsl/build /tmp/tsl/build/config /tmp/tsl/build/config/CMakeFiles/tslconfig.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f config/CMakeFiles/tslconfig.dir/build.make config/CMakeFiles/tslconfig.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'config/CMakeFiles/tslconfig.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 76%] Built target tslconfig
make -f test/CMakeFiles/tsltestframework.dir/build.make test/CMakeFiles/tsltestframework.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/test /tmp/tsl/build /tmp/tsl/build/test /tmp/tsl/build/test/CMakeFiles/tsltestframework.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f test/CMakeFiles/tsltestframework.dir/build.make test/CMakeFiles/tsltestframework.dir/build
make[2]: Entering directory '/tmp/tsl/build'
make[2]: Nothing to be done for 'test/CMakeFiles/tsltestframework.dir/build'.
make[2]: Leaving directory '/tmp/tsl/build'
[ 90%] Built target tsltestframework
make -f app/test/CMakeFiles/test_app.dir/build.make app/test/CMakeFiles/test_app.dir/depend
make[2]: Entering directory '/tmp/tsl/build'
cd /tmp/tsl/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/tsl /tmp/tsl/app/test /tmp/tsl/build /tmp/tsl/build/app/test /tmp/tsl/build/app/test/CMakeFiles/test_app.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/tmp/tsl/build'
make -f app/test/CMakeFiles/test_app.dir/build.make app/test/CMakeFiles/test_app.dir/build
make[2]: Entering directory '/tmp/tsl/build'
[ 93%] Linking C executable test_app
cd /tmp/tsl/build/app/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_app.dir/link.txt --verbose=1
/usr/bin/cc  -g3 -gdwarf-4 -rdynamic -Wall -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Wuninitialized -Wmissing-include-dirs -Wshadow -Wframe-larger-than=2047 -march=native -mtune=native   -rdynamic CMakeFiles/test_app.dir/test_app.c.o  -o test_app -ljansson ../../test/libtsltestframework.a ../libtslapp.a ../../config/libtslconfig.a ../../tsl/libtsl.a -lck
../../config/libtslconfig.a(engine.c.o): In function `json_decref':
/usr/include/jansson.h:129: undefined reference to `json_delete'
../../config/libtslconfig.a(engine.c.o): In function `__config_from_json':
/tmp/tsl/config/engine.c:74: undefined reference to `json_array_size'
/tmp/tsl/config/engine.c:78: undefined reference to `json_integer_value'
/tmp/tsl/config/engine.c:82: undefined reference to `json_string_value'
/tmp/tsl/config/engine.c:94: undefined reference to `json_real_value'
../../config/libtslconfig.a(engine.c.o): In function `config_new':
/tmp/tsl/config/engine.c:124: undefined reference to `json_object'
../../config/libtslconfig.a(engine.c.o): In function `config_add':
/tmp/tsl/config/engine.c:162: undefined reference to `json_load_file'
/tmp/tsl/config/engine.c:170: undefined reference to `json_object_update'
../../config/libtslconfig.a(engine.c.o): In function `config_add_string':
/tmp/tsl/config/engine.c:269: undefined reference to `json_loads'
/tmp/tsl/config/engine.c:277: undefined reference to `json_object_update'
../../config/libtslconfig.a(engine.c.o): In function `config_get':
/tmp/tsl/config/engine.c:333: undefined reference to `json_object_get'
../../config/libtslconfig.a(engine.c.o): In function `config_serialize':
/tmp/tsl/config/engine.c:354: undefined reference to `json_dumps'
../../config/libtslconfig.a(engine.c.o): In function `config_array_at':
/tmp/tsl/config/engine.c:426: undefined reference to `json_array_size'
/tmp/tsl/config/engine.c:431: undefined reference to `json_array_get'
collect2: error: ld returned 1 exit status
app/test/CMakeFiles/test_app.dir/build.make:98: recipe for target 'app/test/test_app' failed
make[2]: *** [app/test/test_app] Error 1
make[2]: Leaving directory '/tmp/tsl/build'
CMakeFiles/Makefile2:296: recipe for target 'app/test/CMakeFiles/test_app.dir/all' failed
make[1]: *** [app/test/CMakeFiles/test_app.dir/all] Error 2
make[1]: Leaving directory '/tmp/tsl/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pvachon** [comment] 2020-05-24 00:37
Thanks! I can't reproduce the issue, but https://github.com/pvachon/tsl/commit/63178348d85f9afcbb0a36589fcc927b531e573f fixes the link order and that should resolve your issue.

**Comment by RIKIKU** [comment] 2020-05-24 07:16
can confirm that fixed the issue!

**Comment by pvachon** [comment] 2020-05-24 19:41
Thank you very much for testing. Closing because https://github.com/pvachon/tsl/commit/63178348d85f9afcbb0a36589fcc927b531e573f fixed the problem.

**Closed as completed by pvachon** 2020-05-24 19:41 UTC
